import { readFile, writeFile, mkdir, cp } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
const root = fileURLToPath(new URL('./', import.meta.url));
const [baseline, output] = process.argv.slice(2);
if (!baseline || !output) throw Error('Usage: package.mjs BASELINE_OXIDE_DIR OUTPUT_DIR');
const manifest = JSON.parse(await readFile(`${root}dist/manifest.json`, 'utf8'));
const config = JSON.parse(await readFile(`${baseline}/config/RaidableBases.json`, 'utf8'));
const quarantine = JSON.parse(await readFile(`${root}quarantine.json`, 'utf8'));
const excludeKey = 'Templates excluded from random selection (explicit spawning still allowed)';
config[excludeKey] = [...new Set([...(config[excludeKey] ?? []), ...quarantine.templates])];
const baseProfile = JSON.parse(await readFile(`${baseline}/data/RaidableBases/Profiles/RaidBases.json`, 'utf8'));
const groupKey = 'Balanced Base Families (template names grouped by layout)';
config[groupKey] ??= {};
for (const family of new Set(manifest.map(d => d.family))) config[groupKey][family] = manifest.filter(d => d.family === family).map(d => d.id);
await mkdir(`${output}/oxide/config`, { recursive: true });
await mkdir(`${output}/oxide/data/RaidableBases/Profiles`, { recursive: true });
await cp(`${root}dist/copypaste`, `${output}/oxide/data/copypaste`, { recursive: true });
for (const d of manifest) {
  const p = structuredClone(baseProfile);
  p['Additional Bases For This Difficulty'] = {};
  p['Profile Enabled'] = true;
  p['Paste Options'] = [{ Option: 'stability', Value: 'false' }, { Option: 'autoheight', Value: 'false' }, { Option: 'height', Value: '0.8' }];
  p['Advanced Setup Settings']['Amount Of Entities To Spawn Per Batch'] = 1;
  p['Advanced Setup Settings']['Height Adjustment Applied To This Paste'] = 0;
  const radius = Math.ceil(Math.max(...d.edges.map(e => Math.hypot(e.x, e.z))) + 5);
  p['Advanced Protection Radius'] = { 'Maintained Events': radius, 'Manual Events': radius, 'Scheduled Events': radius, 'Obstruction Distance Check': radius };
  p['Maximum Land Level'] = 1;
  p['Validate footprint before paste (including admin aim spawns)'] = true;
  p['Empty All Containers Before Spawning Loot'] = false;
  p['No Item Input For Boxes And TC'] = false;
  p['Skip Treasure Loot And Use Loot In Base Only'] = false;
  p['Minimum Amount Of Items To Spawn (0 = Use Max Value)'] = [0, 8, 15, 22][d.tier];
  p['Amount Of Items To Spawn'] = [0, 12, 22, 30][d.tier];
  p['Loot Amount Multiplier'] = [0, .15, .35, .65][d.tier];
  p['Allow Duplicate Items'] = false;
  p['Always Spawn Base Loot Table'] = false;
  p['Arena Walls'].Enabled = false;
  p.NPCs.Enabled = false;
  p['Spawn Silently (No Notifcation, No Dome, No Map Marker)'] = true;
  p['Create Dome Around Event Using Spheres (0 = disabled, recommended = 5)'] = 0;
  await writeFile(`${output}/oxide/data/RaidableBases/Profiles/${d.id}.json`, JSON.stringify(p, null, 2) + '\n');
}
await writeFile(`${output}/oxide/config/RaidableBases.json`, JSON.stringify(config, null, 2) + '\n');
console.log(`Packaged ${manifest.length} new profiles. Existing profiles/data are not overwritten.`);
