export const build = name => `assets/prefabs/building core/${name}/${name}.prefab`;
export const paths = {
  foundation: build('foundation'), floor: build('floor'), wall: build('wall'),
  doorway: build('wall.doorway'), frame: build('wall.frame'), window: build('wall.window'),
  half: build('wall.half'), stairs: 'assets/prefabs/building core/stairs.l/block.stair.lshape.prefab', ramp: build('ramp'),
  door: 'assets/prefabs/building/door.hinged/door.hinged.metal.prefab',
  woodDoor: 'assets/prefabs/building/door.hinged/door.hinged.wood.prefab',
  armoredDoor: 'assets/prefabs/building/door.hinged/door.hinged.toptier.prefab',
  doubleDoor: 'assets/prefabs/building/door.double.hinged/door.double.hinged.metal.prefab',
  garage: 'assets/prefabs/building/wall.frame.garagedoor/wall.frame.garagedoor.prefab',
  bars: 'assets/prefabs/building/wall.window.bars/wall.window.bars.metal.prefab',
  glass: 'assets/prefabs/building/wall.window.reinforcedglass/wall.window.glass.reinforced.prefab',
  tc: 'assets/prefabs/deployable/tool cupboard/cupboard.tool.deployed.prefab',
  box: 'assets/prefabs/deployable/large wood storage/box.wooden.large.prefab',
  smallBox: 'assets/prefabs/deployable/woodenbox/woodbox_deployed.prefab',
  bag: 'assets/prefabs/deployable/sleeping bag/sleepingbag_leather_deployed.prefab',
  bed: 'assets/prefabs/deployable/bed/bed_deployed.prefab',
  furnace: 'assets/prefabs/deployable/furnace/furnace.prefab',
  bench1: 'assets/prefabs/deployable/tier 1 workbench/workbench1.deployed.prefab',
  bench2: 'assets/prefabs/deployable/tier 2 workbench/workbench2.deployed.prefab',
  bench3: 'assets/prefabs/deployable/tier 3 workbench/workbench3.deployed.prefab',
  research: 'assets/prefabs/deployable/research table/researchtable_deployed.prefab',
  repair: 'assets/prefabs/deployable/repair bench/repairbench_deployed.prefab',
  mixing: 'assets/prefabs/deployable/mixingtable/mixingtable.deployed.prefab',
  bbq: 'assets/prefabs/deployable/bbq/bbq.deployed.prefab',
  lantern: 'assets/prefabs/deployable/lantern/lantern.deployed.prefab',
  chair: 'assets/prefabs/deployable/chair/chair.deployed.prefab',
  table: 'assets/prefabs/deployable/table/table.deployed.prefab',
  planter: 'assets/prefabs/deployable/planters/planter.small.deployed.prefab',
  locker: 'assets/prefabs/deployable/locker/locker.deployed.prefab',
};
